Redone error exit system
rust-secure-code/cargo-supply-chain pull request #65
Opened 2021-05-18 14:12 UTC by Owez

Closes #23

2021-05-18 14:27 UTC, Shnatsel commented
Thanks! I'll try to take a look later today. If I don't, please ping me.

2021-05-19 16:15 UTC, Shnatsel requested changes

2021-05-19 16:15 UTC, Shnatsel commented on src/common.rs
> +        Err(_) => err_exit("Unknown error whilst fetching crate's metadata!"),
Why are we using custom error messages here? `MetadataCommand::new().exec()` already provides perfectly good error messages, I think we can just print them without any matching. I don't want to destroy the informative error messages we get from `cargo metadata` and show only "unknown error" which is not actionable for the user.

For reference, this is the output I get without this PR:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CargoMetadata { stderr: "error: could not find `Cargo.toml` in `/home/shnatsel` or any parent directory\n" }', /home/shnatsel/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-supply-chain-0.1.2/src/common.rs:20:10

2021-05-19 16:17 UTC, Shnatsel commented
In the long term we probably want to return an error from this function instead of exiting the process, but that's not strictly necessary in this PR.

2021-05-19 18:54 UTC, Shnatsel approved these changes

2021-05-19 18:59 UTC, Shnatsel commented
Ugh, I must have botched something in the conflict resolution, and there is no track of the manual changes made during resolution... thank you for nothing, git.

2021-05-19 19:06 UTC, merged

2021-05-19 19:06 UTC, Shnatsel commented
Merged. Thanks!

2021-05-20 11:38 UTC, Owez commented
When does git not mess up :)